feature: Run isolate when create MultipartFileRecreatable object
rodion-m/dio_smart_retry pull request #25
Opened 2023-03-17 16:37 UTC by dafinoer

hi @rodion-m 
we know when the object tries to recreate MultipartFileRecreatable object, will run on the main Isolate memory,

https://github.com/rodion-m/dio_smart_retry/blob/ce295aaea62f8c0e246200f869f9bf2b92d75637/lib/src/retry_interceptor.dart#L181

which is, when the apps try to retry and have Multipart of files, the apps will get decreased performance(jank UI), So I'm trying to change the object recreated from run sync in the main isolate, to run in another memory using isolate.

https://github.com/dafinoer/dio_smart_retry/blob/07e4c1e302e8b2b1d8c437807d73270ba0ba9764/lib/src/retry_interceptor.dart#L185

what do u think?

im sorry if my english so bad. Thank you.

2023-03-18 02:55 UTC, rodion-m commented
Hi! Thank you contributing, I think it's a great idea! Could you please add a test for this feature?

2023-03-30 08:16 UTC, Zazo032 commented
Isolates don't work on the web platform, so you should add a fallback for web to not break it

2023-04-03 10:47 UTC, Zazo032 commented
@dafinoer instead of creating a `.fromIsolate` named constructor, I think it would be helpful to provide sync and async constructors, and you can then use the isolate from your codebase without breaking web builds

2023-04-11 08:25 UTC, rodion-m requested changes

2023-04-11 08:27 UTC, rodion-m commented
> @dafinoer instead of creating a `.fromIsolate` named constructor, I think it would be helpful to provide sync and async constructors, and you can then use the isolate from your codebase without breaking web builds

What's the async constructor?

2023-04-11 15:20 UTC, dafinoer commented on lib/src/retry_interceptor.dart
> +        final filePath = file.filePath;
Nice idea, i will fix that.

2023-04-11 23:02 UTC, Zazo032 commented
> I like this idea. So, if we are on the web, just use sync method, otherwise use async.

Not really, the current implementation relies on `dart:io`, which won't work on the web. On #27 I'm planning to add a bytes-based constructor so it can work on the web.

The idea of the async method was mostly because `Isolate.run` expects a `Future`, but I'm now thinking that you may be able to pass any code by wrapping it into a `Future` (even if it's a sync method).

2023-10-26 15:52 UTC, rodion-m commented
Hey @Zazo032 ! Could you please help me with this PR? I'm interested in your opinion on this issue.

2023-10-26 16:41 UTC, closed without merging

2023-10-26 16:41 UTC, rodion-m commented
@dafinoer  I think it's a bad approach to break Web compatibility. If you come up with some else approach to implementing this, please create an issue or even a PR.